---
- name: target directory exists and is writeable
  file: path={{ target_directory }} state=directory mode=755

- name: download and extract WordPress
  unarchive:
    src=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest={{ target_directory }}
    copy=no
    creates={{ target_directory }}/wordpress

- name: create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  when: wp_create_mysql_db

- name: create WordPress database user
  mysql_user:
    name={{ wp_db_user }}
    password={{ wp_db_password }}
    priv={{ wp_db_name }}.*:ALL
    host='localhost'
    state=present
  when: wp_create_mysql_user

- name: fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: copy WordPress config file
  template: src=wp-config.php.j2 dest={{ target_directory }}/wordpress/wp-config.php
